add success criteria

diff --git a/run b/run
--- a/run
+++ b/run
@@ -204,13 +204,13 @@ mkdir ./tmp
 echo "Converting input files to mrtrix format..."
 
 ## convert input diffusion data into mrtrix format
-mrconvert -fslgrad $BVEC $BVAL $DIFF raw1.mif --export_grad_mrtrix raw1.b -quiet  #  -nthreads $NCORE
+mrconvert -fslgrad $BVEC $BVAL $DIFF raw1.mif --export_grad_mrtrix raw1.b -quiet
 
 ## if the second input exists
 if [[ -e $RDIF ]]; then
 
     ## convert it to mrtrix format
-    mrconvert -fslgrad $RBVC $RBVL $RDIF raw2.mif --export_grad_mrtrix raw2.b -quiet  #  -nthreads $NCORE
+    mrconvert -fslgrad $RBVC $RBVL $RDIF raw2.mif --export_grad_mrtrix raw2.b -quiet
 
 fi
 
@@ -219,33 +219,33 @@ echo "Identifying correct gradient orientation..."
 if [[ $RPE == "all" ]]; then
 
     ## merge them
-    mrcat raw1.mif raw2.mif raw.mif -quiet  #  -nthreads $NCORE
+    mrcat raw1.mif raw2.mif raw.mif -quiet
     cat raw1.b raw2.b > raw.b
 
     echo "Creating processing mask..."
 
     ## create mask from merged data
-    dwi2mask raw.mif ${mask}.mif -force -quiet  #  -nthreads $NCORE
+    dwi2mask raw.mif ${mask}.mif -force -quiet
 
     ## check and correct gradient orientation and create corrected image
-    dwigradcheck raw.mif -grad raw.b -mask ${mask}.mif -export_grad_mrtrix corr.b -force -tempdir ./tmp -quiet  #  -nthreads $NCORE
-    mrconvert raw.mif -grad corr.b ${difm}.mif -quiet  #  -nthreads $NCORE
+    dwigradcheck raw.mif -grad raw.b -mask ${mask}.mif -export_grad_mrtrix corr.b -force -tempdir ./tmp -quiet
+    mrconvert raw.mif -grad corr.b ${difm}.mif -quiet
 
 else
 
     echo "Creating processing mask..."
 
     ## create mask
-    dwi2mask raw1.mif ${mask}.mif -force -quiet  #  -nthreads $NCORE
+    dwi2mask raw1.mif ${mask}.mif -force -quiet
 
     ## check and correct gradient orientation and create corrected image
-    dwigradcheck raw1.mif -grad raw1.b -mask ${mask}.mif -export_grad_mrtrix cor1.b -force -tempdir ./tmp -quiet  #  -nthreads $NCORE
-    mrconvert raw1.mif -grad cor1.b ${difm}.mif -quiet  #  -nthreads $NCORE
+    dwigradcheck raw1.mif -grad raw1.b -mask ${mask}.mif -export_grad_mrtrix cor1.b -force -tempdir ./tmp -quiet
+    mrconvert raw1.mif -grad cor1.b ${difm}.mif -quiet
 
     if [[ -e raw2.mif ]]; then
-	dwi2mask raw2.mif rpe_${mask}.mif -force -quiet  #  -nthreads $NCORE
-	dwigradcheck raw2.mif -grad raw2.b -mask rpe_${mask}.mif -export_grad_mrtrix cor2.b -force -tempdir ./tmp -quiet  #  -nthreads $NCORE
-	mrconvert raw2.mif -grad cor2.b rpe_${difm}.mif -quiet  #  -nthreads $NCORE
+	dwi2mask raw2.mif rpe_${mask}.mif -force -quiet
+	dwigradcheck raw2.mif -grad raw2.b -mask rpe_${mask}.mif -export_grad_mrtrix cor2.b -force -tempdir ./tmp -quiet
+	mrconvert raw2.mif -grad cor2.b rpe_${difm}.mif -quiet
     fi
 
 fi
@@ -258,10 +258,10 @@ if [[ $DO_DENOISE == "true" ]] || [[ $DO_RICN == "true" ]]; then
     fi
 
     echo "Performing PCA denoising..."
-    dwidenoise -extent 5,5,5 -noise fpe_noise.mif ${difm}.mif ${difm}_denoise.mif -quiet  #  -nthreads $NCORE
+    dwidenoise -extent 5,5,5 -noise fpe_noise.mif ${difm}.mif ${difm}_denoise.mif -quiet
 
     if [[ -e rpe_${difm}.mif ]]; then
-	dwidenoise -extent 5,5,5 -noise rpe_noise.mif rpe_${difm}.mif rpe_${difm}_denoise.mif -quiet  # -nthreads $NCORE
+	dwidenoise -extent 5,5,5 -noise rpe_noise.mif rpe_${difm}.mif rpe_${difm}_denoise.mif -quiet
     fi
 
     difm=${difm}_denoise
@@ -279,10 +279,10 @@ fi
 if [[ $DO_DEGIBBS == "true" ]]; then
 
     echo "Performing Gibbs ringing correction..."
-    mrdegibbs -nshifts 20 -minW 1 -maxW 3 ${difm}.mif ${difm}_degibbs.mif -quiet  # -nthreads $NCORE
+    mrdegibbs -nshifts 20 -minW 1 -maxW 3 ${difm}.mif ${difm}_degibbs.mif -quiet
 
     if [[ -e rpe_${difm}.mif ]]; then
-	mrdegibbs -nshifts 20 -minW 1 -maxW 3 rpe_${difm}.mif rpe_${difm}_degibbs.mif -quiet  # -nthreads $NCORE
+	mrdegibbs -nshifts 20 -minW 1 -maxW 3 rpe_${difm}.mif rpe_${difm}_degibbs.mif -quiet
     fi
 
     difm=${difm}_degibbs
@@ -295,7 +295,7 @@ if [[ $DO_EDDY == "true" ]]; then
     if [[ $RPE == "none" ]]; then
 
 	echo "Performing FSL eddy correction..."
-	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_none -pe_dir $ACQD ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp  # -nthreads $NCORE
+	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_none -pe_dir $ACQD ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp
 	difm=${difm}_eddy
 
     fi
@@ -303,7 +303,7 @@ if [[ $DO_EDDY == "true" ]]; then
     if [[ $RPE == "pairs" ]]; then
 
 	echo "Performing FSL topup and eddy correction ..."
-	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_pair -pe_dir $ACQD ${difm}.mif -se_epi rpe_${difm}.mif ${difm}_eddy.mif -tempdir ./tmp  # -nthreads $NCORE
+	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_pair -pe_dir $ACQD ${difm}.mif -se_epi rpe_${difm}.mif ${difm}_eddy.mif -tempdir ./tmp
 	difm=${difm}_eddy
 
     fi
@@ -311,7 +311,7 @@ if [[ $DO_EDDY == "true" ]]; then
     if [[ $RPE == "all" ]]; then
 
 	echo "Performing FSL eddy correction for merged input DWI sequences..."
-	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_all -pe_dir $ACQD ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp  -quiet  # -nthreads $NCORE
+	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_all -pe_dir $ACQD ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp  -quiet
 	difm=${difm}_eddy
 
     fi
@@ -320,7 +320,7 @@ if [[ $DO_EDDY == "true" ]]; then
     if [[ $RPE == "header" ]]; then
 
 	echo "Performing FSL eddy correction for merged input DWI sequences..."
-	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_header ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp -quiet  # -nthreads $NCORE
+	dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_header ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp -quiet
 	difm=${difm}_eddy
 
     fi
@@ -330,12 +330,12 @@ fi
 echo "Creating dwi space b0 reference images..."
 
 ## create b0 and mask image in dwi space on forward direction only
-dwiextract ${difm}.mif - -bzero -quiet | mrmath - mean b0_dwi.mif -axis 3 -quiet  # -nthreads $NCORE
-dwi2mask ${difm}.mif ${mask}.mif -force -quiet  # -nthreads $NCORE
+dwiextract ${difm}.mif - -bzero -quiet | mrmath - mean b0_dwi.mif -axis 3 -quiet
+dwi2mask ${difm}.mif ${mask}.mif -force -quiet
 
 ## convert to nifti for alignment to anatomy later on
-mrconvert b0_dwi.mif -stride 1,2,3,4 b0_dwi.nii.gz -quiet  # -nthreads $NCORE
-mrconvert ${mask}.mif -stride 1,2,3,4 ${mask}.nii.gz  -quiet  # -nthreads $NCORE
+mrconvert b0_dwi.mif -stride 1,2,3,4 b0_dwi.nii.gz -quiet
+mrconvert ${mask}.mif -stride 1,2,3,4 ${mask}.nii.gz  -quiet
 
 ## apply mask to image
 fslmaths b0_dwi.nii.gz -mas ${mask}.nii.gz b0_dwi_brain.nii.gz
@@ -344,7 +344,7 @@ fslmaths b0_dwi.nii.gz -mas ${mask}.nii.gz b0_dwi_brain.nii.gz
 if [[ $DO_BIAS == "true" ]]; then
 
     echo "Performing bias correction with ANTs..."
-    dwibiascorrect -mask ${mask}.mif -ants ${difm}.mif ${difm}_bias.mif -tempdir ./tmp -quiet  # -nthreads $NCORE
+    dwibiascorrect -mask ${mask}.mif -ants ${difm}.mif ${difm}_bias.mif -tempdir ./tmp -quiet
     difm=${difm}_bias
 
 fi
@@ -353,11 +353,11 @@ fi
 if [[ $DO_RICN == "true" ]]; then
 
     echo "Performing Rician background noise removal..."
-    mrinfo ${difm}.mif -export_grad_mrtrix tmp.b  -quiet  # -nthreads $NCORE
-    mrcalc noise.mif -finite noise.mif 0 -if lowbnoisemap.mif  -quiet  # -nthreads $NCORE
-    mrcalc ${difm}.mif 2 -pow lowbnoisemap.mif 2 -pow -sub -abs -sqrt - -quiet | mrcalc - -finite - 0 -if tmp.mif -quiet  # -nthreads $NCORE
+    mrinfo ${difm}.mif -export_grad_mrtrix tmp.b  -quiet
+    mrcalc noise.mif -finite noise.mif 0 -if lowbnoisemap.mif  -quiet
+    mrcalc ${difm}.mif 2 -pow lowbnoisemap.mif 2 -pow -sub -abs -sqrt - -quiet | mrcalc - -finite - 0 -if tmp.mif -quiet
     difm=${difm}_ricn
-    mrconvert tmp.mif -grad tmp.b ${difm}.mif -quiet  # -nthreads $NCORE
+    mrconvert tmp.mif -grad tmp.b ${difm}.mif -quiet
     rm -f tmp.mif tmp.b
 
 fi
@@ -368,14 +368,14 @@ if [[ $DO_NORM == "true" ]]; then
     echo "Performing intensity normalization..."
 
     ## create fa wm mask of input subject
-    dwi2tensor -mask ${mask}.mif  -quiet ${difm}.mif - | tensor2metric  -quiet - -fa - | mrthreshold  -quiet -abs 0.5 - wm.mif   # -nthreads $NCORE
+    dwi2tensor -mask ${mask}.mif  -quiet ${difm}.mif - | tensor2metric  -quiet - -fa - | mrthreshold  -quiet -abs 0.5 - wm.mif
 
     ## dilate / erode fa wm mask for smoother volume
     #maskfilter -npass 3 wm_raw.mif dilate - | maskfilter -connectivity - connect - | maskfilter -npass 3 - erode wm.mif
     ## this looks far too blocky to be useful
 
     ## normalize intensity of generous FA white matter mask to 1000
-    dwinormalise -intensity $NORM ${difm}.mif wm.mif ${difm}_norm.mif -quiet  # -nthreads $NCORE
+    dwinormalise -intensity $NORM ${difm}.mif wm.mif ${difm}_norm.mif -quiet
     difm=${difm}_norm
 
 fi
@@ -393,8 +393,8 @@ if [[ $DO_ACPC == "true" ]]; then
     epi_reg --epi=b0_dwi_brain.nii.gz --t1=${ANAT}.nii.gz --t1brain=${ANAT}_brain.nii.gz --out=dwi2acpc
 
     ## apply the transform w/in mrtrix, correcting gradients
-    transformconvert dwi2acpc.mat b0_dwi_brain.nii.gz ${ANAT}_brain.nii.gz flirt_import dwi2acpc_mrtrix.mat -quiet  # -nthreads $NCORE
-    mrtransform -linear dwi2acpc_mrtrix.mat ${difm}.mif ${difm}_acpc.mif -quiet  # -nthreads $NCORE
+    transformconvert dwi2acpc.mat b0_dwi_brain.nii.gz ${ANAT}_brain.nii.gz flirt_import dwi2acpc_mrtrix.mat -quiet
+    mrtransform -linear dwi2acpc_mrtrix.mat ${difm}.mif ${difm}_acpc.mif -quiet
     difm=${difm}_acpc
 
     ## assign output space label
@@ -409,7 +409,7 @@ if [[ $DO_RESLICE == "true" ]]; then
     ## sed to turn possible decimal into p
     VAL=`echo $NEW_RES | sed s/\\\./p/g`
 
-    mrresize ${difm}.mif -voxel $NEW_RES ${difm}_${VAL}mm.mif -quiet  # -nthreads $NCORE
+    mrresize ${difm}.mif -voxel $NEW_RES ${difm}_${VAL}mm.mif -quiet
     difm=${difm}_${VAL}mm
 
 else
@@ -425,18 +425,18 @@ fi
 echo "Creating $out space b0 reference images..."
 
 ## create final b0 / mask
-dwiextract ${difm}.mif - -bzero -quiet | mrmath - mean b0_${out}.mif -axis 3 -quiet  # -nthreads $NCORE
-dwi2mask ${difm}.mif b0_${out}_brain_mask.mif -quiet  # -nthreads $NCORE
+dwiextract ${difm}.mif - -bzero -quiet | mrmath - mean b0_${out}.mif -axis 3 -quiet
+dwi2mask ${difm}.mif b0_${out}_brain_mask.mif -quiet
 
 ## create output space b0s
-mrconvert b0_${out}.mif -stride 1,2,3,4 b0_${out}.nii.gz -quiet  # -nthreads $NCORE
-mrconvert b0_${out}_brain_mask.mif -stride 1,2,3,4 b0_${out}_brain_mask.nii.gz -quiet  # -nthreads $NCORE
+mrconvert b0_${out}.mif -stride 1,2,3,4 b0_${out}.nii.gz -quiet
+mrconvert b0_${out}_brain_mask.mif -stride 1,2,3,4 b0_${out}_brain_mask.nii.gz -quiet
 fslmaths b0_${out}.nii.gz -mas b0_${out}_brain_mask.nii.gz b0_${out}_brain.nii.gz
 
 echo "Creating preprocessed dwi files in $out space..."
 
 ## convert to nifti / fsl output for storage
-mrconvert ${difm}.mif -stride 1,2,3,4 dwi.nii.gz -export_grad_fsl dwi.bvecs dwi.bvals -export_grad_mrtrix ${difm}.b -json_export ${difm}.json -quiet  # -nthreads $NCORE
+mrconvert ${difm}.mif -stride 1,2,3,4 dwi.nii.gz -export_grad_fsl dwi.bvecs dwi.bvals -export_grad_mrtrix ${difm}.b -json_export ${difm}.json -quiet
 
 ## export a lightly structured text file (json?) of shell count / lmax
 echo "Writing text file of basic sequence information..."
@@ -496,11 +496,11 @@ rm -rf ./tmp
 # Ask Michael how he wants to do this, convert all the previous calls to functions?
 
 
-
-#if [[ $exit_status == 0 ]] && [[ $merge_bval_exit == 0 ]] && [[ $merge_bvec_exit == 0 ]]; then
-  echo -e "$CONTAINER  Done!"
-  exit 0
-#else
-#  echo -e "$CONTAINER  Exiting with failures! (fslmerge=$exit_status, merge_bval=$merge_bval_exit, merge_bvec=$merge_bvec_exit)"
-#  exit 1
-#fi
+## check for the output for success
+if [[ -f ${OUTPUT_DIR}/dwi.nii.gz ]]; then
+    echo "$CONTAINER  Success!"
+    exit 0
+else
+    echo "$CONTAINER  Failure detected. Final dwi data files are missing!"
+    exit 1
+fi
